server:
  port: 8085

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.0.4:3306/urlfeederservice
#    url: jdbc:mysql://127.0.0.1:3307/urlfeederservice
    username:
    password:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  kafka:
    producer:
      bootstrap-servers: 172.17.0.3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer